m-lab/gcp-config

- cmd/stctl/main.go
- internal/stctl/command.go
- transfer/job.go
This change adds a support package for wrapping the storagetransfer API in a simpler operation-oriented interface that the `stctl.Command` package will use. As well, this change includes main and the set of commands planned.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/1)
> Add initial framework for stctl command

- Dockerfile
- cmd/stctl/main.go
- daily-archive-transfers.yaml
This change adds a basic Dockerfile and Cloud Build configuration for applying the stctl configuration to our common projects.
To support using a single cloud build file across multiple projects, this change also includes a new flag to stctl that makes execution conditional on the specified -allowed-projects -- if the command runs in another project, then it will exit cleanly without applying the config.
After merging this change, we will need to setup the Cloud Build triggers in each project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/6)
> Add support for integration with CloudBuild

- cmd/stctl/main.go
- internal/stctl/command.go
- internal/stctl/command_test.go
- internal/stctl/create_test.go
- internal/stctl/sync.go
- internal/stctl/sync_test.go
This change adds support for Command.Sync. This should complete the functionality needed for gcp-config to manage declarative configurations.
A final change will add cloud build automation to run `stctl sync` with the schedule and configs defined in the "Codified Daily Archive Transfers" design.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/5)
> Add Sync support with unit tests

- daily-archive-transfers.yaml
The DISCO export from collectd is scheduled at 10min after the hour for reasonable reasons.
https://github.com/m-lab/collectd-mlab/blob/master/export/mlab_export.cron
The export schedule aligns closely enough with the transfer jobs that some files are not transferred. This change updates the transfer jobs to start at 30min after the hour.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/12)
> Update schedules to half-past the hour

- adhoc/normalize_gcs_archive.sh
This change adds an adhoc script that will be run twice.
1. to perform an rsync between all legacy, parsed datatypes to their canonical `<exp>/<datatype>/YYYY/...` names.
2. to do the same operation again, followed by removing the legacy names.
These steps can optionally be automated using cloud build; let me know if you'd prefer that.
FYI: @pboothe @yachang @critzo
Part of https://github.com/m-lab/dev-tracker/issues/548
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/16)
> Add script with steps to normalize GCS archives

- adhoc/normalize_gcs_archive.sh
This change removes paris-traceroute from the normalization script in favor of plans to reprocess the paris-traceroute data into the annotated-traceroute format generated by the new traceroute-caller.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/18)
> Remove paris-traceroute from normalization

- Dockerfile.golang
- Dockerfile.jsonnet
- cloudbuild.yaml
This change adds two custom Cloud Builder images that will be installed per-project by default. As a result of this change, once deployed, other M-lab repos using Cloud Builder can reference these builders in their own cloudbuild.yaml files, saving build time.
For example, the gcloud-jsonnet-cbif image should speed up k8s-support and siteinfo deploys by eliminating the requirement for creating a jsonnet environment.
The gloang-cbif image should make it possible to run golang tests and report coverage stats to coveralls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/19)
> Add custom golang and gcloud builders enabled with cbif

- Dockerfile.jsonnet
This command was adapted from the step using `wget` in m-lab/siteinfo/Dockerfile -- but wget follows redirets automatically.
This change uses the correct source URL as well as allowing curl to follow redirects in the future.
With this change it should be possible to use the gcloud-jsonnet-cbif builder in siteinfo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/20)
> Update link and allow curl to follow redirects

- Dockerfile.jsonnet
This change adds a new package `jq` to the gcloud+jsonnet builder image so k8s-support can use the per-project image for faster deploys.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/21)
> Add jq to gcloud-jsonnet image

- Dockerfile.epoxy-images
- cloudbuild.yaml
epoxy-images are already slow, having to build the Docker image for Cloud Build slows them down even more. This PR adds a new Dockerfile for epoxy-images, and published it to gcr.io for use by other things, namely epoxy-images builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/22)
> Builds a new Docker image for epoxy-images

- service-accounts/README.md
Add notes on exporting custom roles so that we can capture the configuration in github.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/25)
> Add instructions for exporting custom roles

- service-accounts/public_bigquery_user_dataset_level.yaml
- service-accounts/public_bigquery_user_project_level.yaml
This PR adds two IAM roles used to provide limited project access and access to specific datasets to members of discuss@measurementlab.net
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/26)
> add public discuss group roles

- daily-archive-transfers.yaml
- go.sum
- internal/stctl/create.go
- internal/stctl/create_test.go
- internal/stctl/sync.go
- internal/stctl/sync_test.go
Add separate transfers every six hours.
It is hoped that this will make the transfers faster, so we don't miss the start of parsing.
Also restricts the transfer to files modified in the past 5 days.  Hopefully transfer service can use this to optimize the request.
NOTE: I haven't quite figured out how to create multiple requests.  Changed the description, but that doesn't seem to be adequate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/27)
> Sandbox six hour transfer

- cmd/stctl/main.go
- daily-archive-transfers.yaml
- internal/stctl/command.go
- internal/stctl/create.go
- internal/stctl/create_test.go
- internal/stctl/sync.go
- internal/stctl/sync_test.go
This adds CLI parameters to allow filtering of files based on last mod time.
We hope that this will allow DataTransfer service to be more efficient than if it has to review the entire history.
The config file now imposes 12h age restrictions on 3 of the 4 transfers.  The mid-day transfer has NO age
restriction, so it will handle any old files that were missed in recent transfers.
Q: Should we add a liberal limit for the mid-day transfer, maybe one week or one month?
The PR also includes, for now, commenting out of some lines in the test configs that appear to be superfluous.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/29)
> Add minFileAge and maxFileAge parameters

- daily-archive-transfers.yaml
Looks like the minFileAge of 10 minutes causes the transfer to drag out longer than is useful.  Change to 1 minute, to minimize the long tail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/32)
> change minFileAge to one minute

- daily-archive-transfers.yaml
Based on recent observations about GCS Storage Transfer job completion times, they usually take 3-4.5hrs.
This change creates two daily transfers from p->a and a->a, every 12 hours. The a->a transfer is scheduled 4hrs after the p->a transfer. This delays the availability of all archive data for the previous day, but is more likely to be complete based on recent GCS ST behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/33)
> Two daily archive transfer jobs

- cmd/stctl/main.go
- internal/stctl/command.go
- internal/stctl/command_test.go
- internal/stctl/create.go
- internal/stctl/create_test.go
- internal/stctl/export_test.go
- internal/stctl/sync.go
- internal/stctl/sync_test.go
This is needed to configure transfer rules, particularly from pusher to other buckets.
This does NOT yet change the configuration - just adds the capability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/34)
> Add delete after transfer option to sync command

- cloud-deployment/README.md
- cloud-deployment/logs-based-metrics.yaml
This PR creates a new subdirectory to contain Google Cloud Deployment Manager YAML spec files. It also creates a new spec file for logs-based metrics, creating, for now, a single logs-based metric for platform cluster kernel logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/38)
> Adds cloud-deployment dir with YAML spec for creating logs-based-metrics

- Dockerfile.epoxy-images
This PR is in support of PR https://github.com/m-lab/epoxy-images/pull/201
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/39)
> Installs jq into the epoxy-images Docker image

- daily-archive-transfers.yaml
- internal/stctl/sync.go
This change fixes a bug that resulted in unnecessary recreation of jobs due to poor matching of the transfer condition times.
This change also adds additional debug logging for error cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/41)
> Fix specMatch & add extra logging

- cmd/cbctl/main.go
- internal/cbctl/trigger.go
This change adds a new command line tool to gcp-config: `cbctl`. This tool should help automate the setup of our standard multi-stage development and deployment cycles to sandbox, staging, and mlab-oti.
This tool is useful enough that I am submitting it for review with out unit tests. However, this should not be taken as indication that the tool need not have them, only that it does not have them yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/42)
> Add cbctl to automate creation of cloud build triggers in GCP

- Dockerfile.siteinfo
- cloudbuild.yaml
A number of things currently hinge on changes to siteinfo. For example, currently, when a new site is added to siteinfo, an operator must manually go and trigger a build on the epoxy-images repository to cause boot images to be built for the new site. Same thing for adding ePoxy GCD entities when a new site is added. Same thing for the switch-config repository. This PR is a first step in automating those manual processes. It creates a custom Docker image for the siteinfo repository which contains the `epoxy_admin` and `cbctl` utilities. The former for creating ePoxy GCD entities for a site, the latter for triggering builds of the epoxy-images and switch-config repositories.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Builds custom Docker image for siteinfo repository builds

- cmd/cbctl/main.go
This feature will be used to pass a Github token to `cbctl`'s `-github_token` flag through the environment, not printing it in the Cloud Build logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/48)
> Adds flagx.ArgsFromEnvWithLog(<flagset>, false) to main()

- Dockerfile.siteinfo
- cmd/cbctl/main.go
I realized today that the in-file documentation for `cbctl` was outdated and not sufficient any longer. This PR updates it a bit to make it more useful to someone using it that doesn't already know how to use it.
Also, it updates the `go-github` module to v37.0.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/49)
> Improves in-file documentation for cbctl

- Dockerfile.epoxy-images
This is in preparation for leveraging Go modules (without special env variables) to install versioned CNI plugins inside of stage3 Ubuntu images.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/50)
> Updates Go to v1.16.x in epoxy-images build image

- Dockerfile.golang
Builds of Locate are failing because this build environment is still using Go 1.14. Moving to 1.16 fixes the build, and I will also introduce Go modules to Locate.
There are [maybe six other repositories](https://github.com/search?q=org%3Am-lab+golang-cbif&type=code) using the image built by this Dockerfile. It's not impossible that this change could break builds in those repos. But my thinking is that we have to keep moving into the present and future, and if this change does for some odd reason break some other build that requires this image, then the right thing to do will be to make updates to that repo to support at least version 1.16 of Go.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Updates Go to 1.16 in Dockerfile.golang

- adhoc/normalize_gcs_archive.sh
Copy legacy scamper data for the `host` and `neubot` experiments.
Also, added forward slash to the `rsync` command for `ndt` for consistency with the original commands.
Data copied in sandbox:
**host**
https://pantheon.corp.google.com/storage/browser/archive-mlab-sandbox/host/scamper1?project=mlab-sandbox&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false
**neubot**
https://pantheon.corp.google.com/storage/browser/archive-mlab-sandbox/neubot/scamper1?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&project=mlab-sandbox&prefix=&forceOnObjectsSortingFiltering=false
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Add legacy scamper copy for host and neubot

- Dockerfile.jsonnet
Jsonnet 0.15.0 brought in new features I wanted (`std.member()`), but the version of sjsonnet did not have them. This PR just brings sjsonnet up to date.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/55)
> Updates sjsonnet to 0.4.2

- adhoc/normalize_gcs_archive.sh
This was run in sandbox.
The only folder that remained is [archive-mlab-sandbox/ndt/traceroute/](https://pantheon.corp.google.com/storage/browser/archive-mlab-sandbox/ndt/traceroute;tab=objects?project=mlab-sandbox&prefix=&forceOnObjectsSortingFiltering=false) because it has two files that did not belong to any of the year sub-folders. I checked the other ndt/host/neubot buckets in staging and oti and they don't have any straggler files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/56)
> Remove legacy scamper files in GCS

- daily-archive-transfers.yaml
This change adds a new daily transfer configuration for thirdparty revtr data uploaded to `thirdparty-revtr-mlab-oti` GCS bucket. This change will publish all datatypes under the `gs://thirdparty-revtr-mlab-oti/revtr/` directory to the public `gs://archive-measurement-lab/revtr`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/57)
> Add daily transfer job for thirdparty-revtr

- Dockerfile.golang
- Dockerfile.jsonnet
- cloudbuild.yaml
This change updates the `golang-cbif:1.18` and `gcloud-jsonnet-cbif:1.18` images to use go1.18 and explicitly tags the image version based on the Go version (i.e. 1.18). Previously, our builds (and users of these images) unconditionally used the 'latest' tag. Due to the differences between go1.18 and earlier versions, this change introduces explicit image version tags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/58)
> Update to golang 1.18, with tagged builds

- daily-archive-transfers.yaml
This change enables `deleteAfterTransfer` for the archive-mlab-oti to archive-measurement-lab daily transfers. Since mlab-oti is the production project (hence most data) and this data's final destination is archive-measurement-lab (unlike archive-mlab-sandbox and archive-mlab-staging which are terminal locations), and our data pipeline sources data from archive-measurement-lab, we can safely enable `deleteAfterTransfer` for archive-mlab-oti.
Part of:
* https://github.com/m-lab/dev-tracker/issues/729
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/60)
> Delete after transfer from archive to archive

- cmd/cbctl/main.go
The regular expressions for matching branch and tag names was unbounded,
possibly causing unintended matching. Additionally, this commit removes
the -projects flag and hardcodes the 3 M-Lab projects. It also renamed
the operation "create-projects" to "create-mlab-projects".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/62)
> Bounds regexp for matching branch

- Dockerfile.epoxy-images
- Dockerfile.golang
- Dockerfile.siteinfo
- cloudbuild.yaml
This change completes the update to golang:1.18 for all Dockerfiles in this repo.
All generated images are now versioned. Previously untagged images will continue to work, but dependencies (e.g. siteinfo) should be migrated to the latest tagged version for consistency.
Part of:
* https://github.com/m-lab/dev-tracker/issues/735
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/63)
> Update to use go1.18 and generate versioned images

- cloud-build-notifiers/README.md
- cloud-build-notifiers/slack-configuration.yaml
- cloud-build-notifiers/slack-message-template.json
These config files were used to enable [Slack Cloud Build notifications](https://cloud.google.com/build/docs/configuring-notifications/automate) in each project. I'm adding them to this repository for lack of a better place to put them, along with a brief bit of documentation on how this was done for each project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/65)
> Adds config files for the Slack Cloud Build notifier

- Dockerfile.epoxy-images
This is a a setup step which will enable building custom cloud images using Hashicorp Packer in epoxy-images builds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/67)
> Install Hashicorp Packer into epoxy-images image

- Dockerfile
- Dockerfile.epoxy-images
- Dockerfile.golang
- Dockerfile.jsonnet
- Dockerfile.siteinfo
- cloudbuild.yaml
This change updates the gcp-config image builds to use golang 1.20. The previous versions will remain in the GCR so no current dependencies will break. This change enables cloud builds that depend on go1.20.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/68)
> Update golang version to 1.20

- internal/stctl/sync.go
Through the storage transfers UI, it is possible to create a job without a `Schedule` object. If this is the case, `stctl` will segfault when trying to access an object within the `nil` Schedule object. This change checks for this case and skips it also.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/69)
> Skip nil job.Schedule

- daily-archive-transfers.yaml
This PR sets up a sync for a dedicated transfer job of autoloaded data.
The job runs hourly. It only transfers data under the "autoload" prefix from the pusher bucket to the archive bucket.
https://pantheon.corp.google.com/transfer/jobs/transferJobs%2F10435470182208531695/configuration?project=mlab-sandbox
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/71)
> Set up sync for dedicated autoload transfer job

- daily-archive-transfers.yaml
This PR adds a new job to transfer autoloaded data from "archive-mlab-oti" to "archive-measurement-lab".
The job will be edited to an hourly frequency after creation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/72)
> Add job to transfer autoloaded data to measurement-lab

- daily-archive-transfers.yaml
This PR includes the `msak/` prefix to the list of prefixes to copy from the pusher bucket to the archive bucket.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/74)
> Add the msak prefix to daily transfer jobs from pusher to archive

- .travis.yml
- Dockerfile
- Dockerfile.epoxy-images
- Dockerfile.golang
- Dockerfile.jsonnet
- Dockerfile.siteinfo
- cloudbuild.yaml
- go.mod
This PR changes the Go version back to 1.20. For more details, see [this](https://github.com/m-lab/dev-tracker/issues/771#issuecomment-1690008862) comment.
I've cleaned up the container registry versions corresponding to Go 1.21.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/76)
> Change Go version back to 1.20

- Dockerfile
- cmd/stctl/main.go
- daily-archive-transfers.yaml
- internal/stctl/command.go
- internal/stctl/create.go
- internal/stctl/sync.go
- internal/stctl/sync_test.go
This PR adds an option to specify a repeat interval for transfer jobs.
It replaces previous 1 hour intervals previously set through the Transfer Job UI and it adds 1 hour transfers for revtr data.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/78)
> Add option to specify interval for transfer jobs

- daily-archive-transfers.yaml
Missing this was an oversight! There was some data under `gs://archive-measurement-lab/autoload/v1/revtr/*` and I thought that was from the transfer job.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/79)
> Add autoload prefix to transfer job

- cloudbuild.yaml
Today, most all of our Cloud Build images are stored in Container Registry. Container Registry still works but is deprecated. Artifact Registry is far more flexible and configurable.
This PR creates Artifact Registry images for all the images that we currently create in Container Registry. Having both should allow us to slowly migrate to Artifact Registry.  The new "build-images" AR repository publicly readable, meaning that we will be able to use the images from mlab-oti to build things in other production projects like mlab-autojoin and measurement-lab without the need for special service accounts and permissions.
Related PR in terraform-support: https://github.com/m-lab/terraform-support/pull/71
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Create Artifact Registry images
